# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dna_simulator(object):
    def setupUi(self, dna_simulator):
        dna_simulator.setObjectName("dna_simulator")
        dna_simulator.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(dna_simulator)
        self.centralwidget.setObjectName("centralwidget")
        self.loadInputLabel = QtWidgets.QLabel(self.centralwidget)
        self.loadInputLabel.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.loadInputLabel.setObjectName("loadInputLabel")
        self.browsePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.browsePushButton.setGeometry(QtCore.QRect(680, 20, 93, 28))
        self.browsePushButton.setIconSize(QtCore.QSize(16, 16))
        self.browsePushButton.setObjectName("browsePushButton")
        self.filenamePlainEt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.filenamePlainEt.setGeometry(QtCore.QRect(130, 20, 531, 28))
        self.filenamePlainEt.setObjectName("filenamePlainEt")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 391, 61))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 30, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(270, 30, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 391, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(140, 20, 82, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 220, 391, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(250, 50, 71, 16))
        self.label_6.setObjectName("label_6")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_3.setGeometry(QtCore.QRect(250, 20, 41, 28))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(110, 50, 55, 16))
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setGeometry(QtCore.QRect(110, 20, 41, 28))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_2.setGeometry(QtCore.QRect(180, 20, 41, 28))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(180, 50, 55, 16))
        self.label_5.setObjectName("label_5")
        dna_simulator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dna_simulator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        dna_simulator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dna_simulator)
        self.statusbar.setObjectName("statusbar")
        dna_simulator.setStatusBar(self.statusbar)

        self.retranslateUi(dna_simulator)
        QtCore.QMetaObject.connectSlotsByName(dna_simulator)

    def retranslateUi(self, dna_simulator):
        _translate = QtCore.QCoreApplication.translate
        dna_simulator.setWindowTitle(_translate("dna_simulator", "dna_simulator"))
        self.loadInputLabel.setText(_translate("dna_simulator", "Load input file:"))
        self.browsePushButton.setText(_translate("dna_simulator", "Browse"))
        self.groupBox.setTitle(_translate("dna_simulator", "Synthesis:"))
        self.radioButton.setText(_translate("dna_simulator", "RadioButton"))
        self.radioButton_2.setText(_translate("dna_simulator", "RadioButton"))
        self.radioButton_3.setText(_translate("dna_simulator", "RadioButton"))
        self.groupBox_2.setTitle(_translate("dna_simulator", "Sequencing:"))
        self.radioButton_4.setText(_translate("dna_simulator", "RadioButton"))
        self.radioButton_5.setText(_translate("dna_simulator", "RadioButton"))
        self.groupBox_3.setTitle(_translate("dna_simulator", "Priorities:"))
        self.label_6.setText(_translate("dna_simulator", "Substitution"))
        self.label_4.setText(_translate("dna_simulator", "Deletion"))
        self.label_5.setText(_translate("dna_simulator", "Insertion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dna_simulator = QtWidgets.QMainWindow()
    ui = Ui_dna_simulator()
    ui.setupUi(dna_simulator)
    dna_simulator.show()
    sys.exit(app.exec_())
